"""empty message

Revision ID: 165bc4ea228e
Revises: e5dec4b7d95c
Create Date: 2024-11-09 20:11:13.523131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165bc4ea228e'
down_revision = 'e5dec4b7d95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_photo', sa.String(length=500), nullable=True))
        batch_op.alter_column('sound',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.alter_column('sound',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('picture_photo')

    # ### end Alembic commands ###
