"""empty message

Revision ID: a56b60e41878
Revises: 
Create Date: 2024-11-10 01:33:02.314920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56b60e41878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('gallery', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('custom_explanation', sa.Text(), nullable=False),
    sa.Column('custom_question', sa.Text(), nullable=True),
    sa.Column('sound', sa.String(length=500), nullable=True),
    sa.Column('picture_photo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_picture_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=200), nullable=True),
    sa.Column('receiver', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], name='fk_chat_picture_id_picture'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='fk_sentence_chat_id_chat'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence')
    op.drop_table('chat')
    op.drop_table('picture')
    op.drop_table('user')
    # ### end Alembic commands ###
