"""empty message

Revision ID: e5dec4b7d95c
Revises: 
Create Date: 2024-11-09 17:08:32.123425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dec4b7d95c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sound', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_picture_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picture', schema=None) as batch_op:
        batch_op.drop_constraint('fk_picture_user_id_user', type_='foreignkey')
        batch_op.drop_column('sound')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
